
import * as functions from "firebase-functions";
import * as admin from "firebase-admin";

admin.initializeApp();

const GEMINI_API_KEY = functions.config().google.api_key;
const GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent";

interface TranscriptionRequest {
    meetingId: string;
    storagePath: string;
    mimeType: string;
}

export const transcribeAudio = functions.https.onCall(async (data: TranscriptionRequest, context) => {
    // 1. Auth Validation
    if (!context.auth) {
        throw new functions.https.HttpsError(
            "unauthenticated",
            "The function must be called while authenticated."
        );
    }

    const { meetingId, storagePath, mimeType } = data;

    if (!meetingId || !storagePath || !mimeType) {
        throw new functions.https.HttpsError(
            "invalid-argument",
            "The function must be called with meetingId, storagePath, and mimeType."
        );
    }

    if (!GEMINI_API_KEY) {
        throw new functions.https.HttpsError(
            "failed-precondition",
            "Gemini API Key is not configured in functions config."
        );
    }

    try {
        console.log(`[Transcription] Starting for meeting ${meetingId}, path: ${storagePath}`);

        // 2. Download File from Storage
        const bucket = admin.storage().bucket();
        const file = bucket.file(storagePath);

        // Check if exists
        const [exists] = await file.exists();
        if (!exists) {
            throw new functions.https.HttpsError(
                "not-found",
                `File not found at path: ${storagePath}`
            );
        }

        // Download to memory (Buffer)
        // Note: For very large files, a temporary local file or stream might be better,
        // but Cloud Functions memory limit (up to 2GB) usually handles normal audio files fine.
        const [fileBuffer] = await file.download();
        const base64Audio = fileBuffer.toString('base64');

        console.log(`[Transcription] File downloaded. Size: ${fileBuffer.length} bytes`);

        // 3. Call Gemini API
        // We use the REST API directly avoiding the large client library dependency for this simple call
        console.log('[Transcription] Sending to Gemini...');

        const geminiRequest = {
            contents: [{
                parts: [
                    { text: "Veuillez transcrire cet enregistrement audio de réunion en texte. Identifiez les différents interlocuteurs si possible. Structurez la réponse avec des points clairs." },
                    {
                        inline_data: {
                            mime_type: mimeType,
                            data: base64Audio
                        }
                    }
                ]
            }]
        };

        // Note: We need 'fetch' which is available globally in Node 18+ (bundled in firebase functions engine 18)
        // If older node, consider 'axios' or 'node-fetch'
        const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(geminiRequest)
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error('[Gemini API Error]', errorText);
            throw new functions.https.HttpsError(
                "internal",
                `Gemini API refused the request: ${response.status} ${response.statusText}`
            );
        }

        const result: any = await response.json();
        const transcription = result.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!transcription) {
            throw new functions.https.HttpsError("internal", "No transcription generated by Gemini.");
        }

        console.log('[Transcription] Success!');

        // 4. Update Firestore directly
        await admin.firestore().doc(`meetings/${meetingId}`).update({
            'audioRecording.transcription': transcription,
            'audioRecording.transcriptionStatus': 'completed',
            'audioRecording.transcribedAt': new Date().toISOString(),
            dateUpdated: new Date().toISOString()
        });

        return { success: true, transcription };

    } catch (error) {
        console.error('[Transcription Error]', error);

        // Update status to error in Firestore
        await admin.firestore().doc(`meetings/${meetingId}`).update({
            'audioRecording.transcriptionStatus': 'error',
            'audioRecording.transcriptionError': error instanceof Error ? error.message : "Unknown error",
            dateUpdated: new Date().toISOString()
        });

        throw new functions.https.HttpsError("unknown", error instanceof Error ? error.message : "Unknown error");
    }
});
